package com.duan1.ui;

import com.duan1.dao.NhanVienDAO;
import com.duan1.dao.SinhVienDAO;
import com.duan1.ultils.Auth;
import com.duan1.ultils.MsgBox;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

public class DoiMatKhauJDialog extends javax.swing.JDialog {

    public DoiMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDongY = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();
        btnHuyBo = new javax.swing.JButton();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lblMatKhauCu = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JTextField();
        lblMatKhauMoi1 = new javax.swing.JLabel();
        txtMatKhauMoi1 = new javax.swing.JTextField();
        lblMatKhauMoi2 = new javax.swing.JLabel();
        txtMatKhauMoi2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDongY.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnDongY.setText("Đồng ý");
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });
        getContentPane().add(btnDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 100, -1));

        lblQuenMatKhau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 210, -1));

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTaiKhoan.setText("Tài khoản:");
        getContentPane().add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 108, -1, -1));

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 146, 470, 40));

        lblMatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMatKhauCu.setText("Mật khẩu cũ:");
        getContentPane().add(lblMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 204, -1, -1));

        txtMatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 242, 480, 40));

        lblMatKhauMoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMatKhauMoi1.setText("Mật khẩu mới:");
        getContentPane().add(lblMatKhauMoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 300, -1, -1));

        txtMatKhauMoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtMatKhauMoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 338, 480, 40));

        lblMatKhauMoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMatKhauMoi2.setText("Nhập lại mật khẩu mới:");
        getContentPane().add(lblMatKhauMoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 396, -1, -1));

        txtMatKhauMoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtMatKhauMoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 434, 480, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 492, 490, 10));

        lblNen.setBackground(new java.awt.Color(141, 172, 212));
        lblNen.setOpaque(true);
        getContentPane().add(lblNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        if (checkForm()) {
             this.doiMatKhau();
        }       
    }//GEN-LAST:event_btnDongYActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        // TODO add your handling code here:
        this.huyBo();
    }//GEN-LAST:event_btnHuyBoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMatKhauCu;
    private javax.swing.JLabel lblMatKhauMoi1;
    private javax.swing.JLabel lblMatKhauMoi2;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JTextField txtMatKhauCu;
    private javax.swing.JTextField txtMatKhauMoi1;
    private javax.swing.JTextField txtMatKhauMoi2;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
    }

    NhanVienDAO nvdao = new NhanVienDAO();
    SinhVienDAO svdao = new SinhVienDAO();
    Border boder;

    private void doiMatKhau() {

        // nhân viên
        String manv = txtTaiKhoan.getText();
        String matKhau = txtMatKhauCu.getText();
        String matKhauMoi = txtMatKhauMoi1.getText();
        String matKhauMoi2 = txtMatKhauMoi2.getText();

        // sinh viên
        String masv = txtTaiKhoan.getText();
        String matKhauSV = txtMatKhauCu.getText();
        String matKhauMoiSV = txtMatKhauMoi1.getText();
        String matKhauMoiSV2 = txtMatKhauMoi2.getText();

        if (Auth.user != null) {
            // nhân viên
            if (!manv.equalsIgnoreCase(Auth.user.getMaNV())) {
                MsgBox.alert(this, "Sai tên đăng nhập nhân viên!");
            } else if (!matKhau.equals(Auth.user.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu nhân viên!");
            } else if (!matKhauMoi.equals(matKhauMoi2)) {
                MsgBox.alert(this, "Xác nhận mật khẩu nhân viên không đúng!");
            } else {
                Auth.user.setMatKhau(matKhauMoi);
                nvdao.update(Auth.user);
                MsgBox.alert(this, "Đổi mật khẩu nhân viên thành công!");
            }
        } else {
            // sinh viên
            if (!masv.equalsIgnoreCase(Auth.usersv.getMaSV())) {
                MsgBox.alert(this, "Sai tên đăng nhập sinh viên!");
            } else if (!matKhauSV.equals(Auth.usersv.getMatKhauSV())) {
                MsgBox.alert(this, "Sai mật khẩu sinh viên!");
            } else if (!matKhauMoiSV.equals(matKhauMoiSV2)) {
                MsgBox.alert(this, "Xác nhận mật khẩu sinh viên không đúng!");
            } else {
                Auth.usersv.setMatKhauSV(matKhauMoiSV);
                svdao.update(Auth.usersv);
                MsgBox.alert(this, "Đổi mật khẩu sinh viên thành công!");
            }
        }

    }

    private void huyBo() {
        this.dispose();
    }

    public boolean checkForm() {
        // tài khoản
        if (txtTaiKhoan.getText().trim().length() == 0) {
            MsgBox.alert(this, "Nhập tên tài khoản !");
            txtTaiKhoan.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtTaiKhoan.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtTaiKhoan.setBorder(boder);
        }

        // mật khau cu
        if (txtMatKhauCu.getText().trim().length() == 0) {
            MsgBox.alert(this, "Nhập mật khẩu hiện tại !");
            txtMatKhauCu.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtMatKhauCu.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMatKhauCu.setBorder(boder);
        }

        // mat khau moi
        if (txtMatKhauMoi1.getText().trim().length() == 0) {
            MsgBox.alert(this, "Nhập mật khẩu mới !");
            txtMatKhauMoi1.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtMatKhauMoi1.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMatKhauMoi1.setBorder(boder);
        }

        // mat khau moi 2
        if (txtMatKhauMoi2.getText().trim().length() == 0) {
            MsgBox.alert(this, "Xác nhận lại mật khẩu mới !");
            txtMatKhauMoi2.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtMatKhauMoi2.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMatKhauMoi2.setBorder(boder);
        }
        return true;
    }

}
