/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import com.duan1.dao.NhanVienDAO;
import com.duan1.entity.NhanVien;
import com.duan1.ultils.Auth;
import com.duan1.ultils.MsgBox;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author DELL
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhauJDialog
     */
    javax.swing.Timer t;

    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuenMatKhau = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuiMail = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        prgRun = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaXacNhan = new javax.swing.JTextField();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        txtMatKhauMoi1 = new javax.swing.JPasswordField();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        chkHienThiMK = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuenMatKhau.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setText("QUÊN MẬT KHẨU");
        getContentPane().add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 210, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Địa chỉ email:");

        btnGuiMail.setForeground(new java.awt.Color(255, 255, 102));
        btnGuiMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/sendmail.png"))); // NOI18N
        btnGuiMail.setText("Gửi");
        btnGuiMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMailActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 431, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuiMail)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 140));

        btnQuayLai.setForeground(new java.awt.Color(204, 0, 0));
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/exit.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 140, 40));

        prgRun.setIndeterminate(true);
        prgRun.setOpaque(true);
        getContentPane().add(prgRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 670, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xác nhận", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 153, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã xác nhận:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tên đăng nhập:");

        txtMaXacNhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaXacNhan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenDangNhap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mật khẩu mới:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nhập lại mật khẩu mới:");

        btnXacNhan.setForeground(new java.awt.Color(0, 0, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/ok.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận đổi mật khẩu");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnXacNhan.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnXacNhan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtMatKhauMoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMatKhauMoi1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtMatKhauMoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMatKhauMoi2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkHienThiMK.setText("Hiển thị mật khẩu???");
        chkHienThiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHienThiMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(chkHienThiMK)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXacNhan))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(chkHienThiMK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, 260));

        jLabel8.setBackground(new java.awt.Color(141, 172, 212));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMailActionPerformed
        // TODO add your handling code here:
        this.guiMa("huypvnps18997@fpt.edu.vn", "0343946740");
    }//GEN-LAST:event_btnGuiMailActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhapJDialog(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        this.doiMK();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void chkHienThiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHienThiMKActionPerformed
        // TODO add your handling code here:
        if (chkHienThiMK.isSelected()) {
            txtMatKhauMoi1.setEchoChar((char) 0);
            txtMatKhauMoi2.setEchoChar((char) 0);
        } else {
            txtMatKhauMoi1.setEchoChar('*');
            txtMatKhauMoi2.setEchoChar('*');
        }
    }//GEN-LAST:event_chkHienThiMKActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMail;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JCheckBox chkHienThiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JProgressBar prgRun;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacNhan;
    private javax.swing.JPasswordField txtMatKhauMoi1;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO dao = new NhanVienDAO();
    int MaXacNhan = 0;

    private void init() {
        setLocationRelativeTo(null);
    }

    // rỗng mail
    public boolean rongMail() {
        Border boder;
        if (txtEmail.getText().trim().length() == 0) {
            MsgBox.alert(this, "Nhập email cần gửi mã xác nhận !");
            txtEmail.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtEmail.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtEmail.setBorder(boder);
        }
        return true;
    }

    void guiMa(String accountN, String accountP) {
        if (rongMail() == true) {
            Random rd = new Random();
            MaXacNhan = 10000 + rd.nextInt(99999);
            try {
                Properties p = new Properties();
                p.put("mail.smtp.auth", "true");
                p.put("mail.smtp.starttls.enable", "true");
                p.put("mail.smtp.host", "smtp.gmail.com");
                p.put("mail.smtp.port", 587);
                String acountName = accountN;
                String acountpass = accountP;
                Session s = Session.getInstance(p,
                        new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(acountName, acountpass);
                    }
                });
                s.getProperties().put("mail.smtp.ssl.trust", "smtp.gmail.com");
                s.getProperties().put("mail.smtp.starttls.enable", "true");
                ///3.Tạo ra đối tượng message để truyền thông tin mail vào
                String user_from = "EdUSys-CiTy";
                String user_to = txtEmail.getText();
                String subject = "Quên mật khẩu !!!! ";
                String content = "Mã xác nhận đặt lại mật khẩu của bạn là: " + MaXacNhan;
                Message msg = new MimeMessage(s);
                msg.setFrom(new InternetAddress(user_from));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(user_to));
                msg.setSubject(subject);
                msg.setText(content);

                Transport.send(msg);

                MsgBox.alert(this, "Gửi thành công. Vui lòng kiểm tra Mail !");
            } catch (Exception e) {
                MsgBox.alert(this, "Gửi thất bại !");
                e.printStackTrace();
            }

        }

    }

    private void doiMK() {
        String manv = txtTenDangNhap.getText();
        NhanVien nv = dao.selectById(manv);
        if (this.checkma() == true) {
            if (!txtTenDangNhap.equals("")) {
                if (nv == null) {
                    MsgBox.alert(this, "Tên đăng nhập không tồn tại !");
                    boder = BorderFactory.createLineBorder(Color.red);
                    txtTenDangNhap.setBorder(boder);
                    txtTenDangNhap.requestFocus();
                    return;
                } else {
                    Auth.user = nv;
                    MsgBox.alert(this, "Tên đăng nhập đúng!");
                    boder = BorderFactory.createLineBorder(Color.white);
                    txtTenDangNhap.setBorder(boder);
                }

                String matKhauMoi1 = new String(txtMatKhauMoi1.getPassword());
                String matKhauMoi2 = new String(txtMatKhauMoi2.getPassword());
                if (this.checkMK() == true) {
                    if (!matKhauMoi1.equals(matKhauMoi2)) {
                        MsgBox.alert(this, "Xác nhận mật khẩu không trùng khớp!");
                        boder = BorderFactory.createLineBorder(Color.red);
                        txtMatKhauMoi2.setBorder(boder);
                        txtMatKhauMoi2.requestFocus();
                        return;
                    } else {
                        Auth.user.setMatKhau(matKhauMoi1);
                        dao.update(Auth.user);
                        MsgBox.alert(this, "Đổi mật khẩu thành công!");
                        boder = BorderFactory.createLineBorder(Color.white);
                        txtMatKhauMoi2.setBorder(boder);
                        txtMaXacNhan.setEnabled(true);
                        this.clearForm();
                    }
                }
            } else {
                MsgBox.alert(this, "Thất bại!");
            }
        }
    }

    Border boder;

    boolean checkma() {

        // rỗng
        if (txtMaXacNhan.getText().trim().length() == 0) {
            MsgBox.alert(this, "Nhập mã xác nhận !");
            txtMaXacNhan.requestFocus();
            boder = BorderFactory.createLineBorder(Color.red);
            txtMaXacNhan.setBorder(boder);
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMaXacNhan.setBorder(boder);
        }

        if (!txtMaXacNhan.getText().equalsIgnoreCase(String.valueOf(MaXacNhan))) {
            MsgBox.alert(this, "Mã xác nhận không đúng!");
            txtMaXacNhan.setText("");
            boder = BorderFactory.createLineBorder(Color.red);
            txtMaXacNhan.setBorder(boder);
            txtTenDangNhap.setEnabled(false);
            txtMatKhauMoi1.setEnabled(false);
            txtMatKhauMoi2.setEnabled(false);
            txtMaXacNhan.requestFocus();
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMaXacNhan.setBorder(boder);
            MsgBox.alert(this, "Mã xác nhận hợp lệ");
            txtTenDangNhap.setEnabled(true);
            txtMatKhauMoi1.setEnabled(true);
            txtMatKhauMoi2.setEnabled(true);
            txtMaXacNhan.setEnabled(false);
        }

        return true;
    }

    boolean checkMK() {
        String mk = new String(txtMatKhauMoi1.getPassword());
        if (mk.trim().length() < 3) {
            MsgBox.alert(this, "Mật khẩu không đạt yêu cầu bảo mật! Phải từ 3 --> 20 kí tự");
            boder = BorderFactory.createLineBorder(Color.red);
            txtMatKhauMoi1.setBorder(boder);
            txtMatKhauMoi2.setBorder(boder);
            txtMatKhauMoi1.requestFocus();
            return false;
        } else if (mk.trim().length() > 20) {
            MsgBox.alert(this, "Mật khẩu quá kí tự cho phép! Tối đa 20 kí tự");
            boder = BorderFactory.createLineBorder(Color.red);
            txtMatKhauMoi1.setBorder(boder);
            txtMatKhauMoi2.setBorder(boder);
            txtMatKhauMoi1.requestFocus();
            return false;
        } else {
            boder = BorderFactory.createLineBorder(Color.white);
            txtMatKhauMoi1.setBorder(boder);
            txtMatKhauMoi2.setBorder(boder);
        }
        return true;
    }

    void clearForm() {
        txtEmail.setText("");
        txtMaXacNhan.setText("");
        txtTenDangNhap.setText("");
        txtMatKhauMoi1.setText("");
        txtMatKhauMoi2.setText("");
        txtEmail.requestFocus();
    }
}
